# Generated by Django 3.2.2 on 2021-05-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_path_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='img',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
