# Generated by Django 3.2.2 on 2021-05-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_path_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='img',
        ),
    ]
